### ISSUE TITLE
Slow performance backdrop blur

### ISSUE THREAD

**Issue by benjaminpreiss** [filecoin-project/saturn-website#19]
As can be seen in this thread, backdrop blur has massive performance implications.

Adding will-change-transform did not help.

Best to remove backdrop blur and replace with a static background color.

**Comment by benjaminpreiss** [comment]
Performance on slow computers still bad.

Possible solutions:
- Check for device performance. Only use backdrop blur on high performance devices
- Completely disable backdrop blur and exchange with full opacity colors.

**Comment by benjaminpreiss** [comment]
Add `will-change-transform` first and check results

**Comment by NadiemM** [comment]
- Get gpuTier in useEffect
- Assign Tier to tierState 
- default tier 0
- If gpuTier > 2 assign to tierState

**Comment by benjaminpreiss** [comment]
**Important Note:** Utilize context to pass tier to components.
